Examples/WebApp/WebApp/Models/mdlTestResult.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Models
{
    public class mdlTestResult
    {
        public bool testResult { get; set; }
    }
}

Examples/WebApp/WebApp/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using WebApp.Models;
using WebApp.bizObjects;

using Unsafe.Data;
using Unsafe.Data.Common.Validators;
using Unsafe.MVC;

namespace WebApp.Controllers
{

    public class AjaxController : Controller
    {

        #region api - checkSomeID

        [HttpPost()]
        public ActionResult checkSomeID(UnsafeValue testValue)
        {
            mdlTestResult ret = new mdlTestResult();

            ret.testResult = testValue.Validate<valID>().isValid; // note: this validator is in the Unsafe.Data.Common.Validators namespace

            return Json(ret);
        }

        #endregion
        #region api - checkPosInt

        [HttpPost()]
        public ActionResult checkPosInt(UnsafeValue testValue)
        {
            mdlTestResult ret = new mdlTestResult();

            ret.testResult = testValue.Validate<valPosInteger>().isValid; // note: this is a custom validator in this project's bizObjects namespace

            return Json(ret);
        }

        #endregion
        #region api - checkNegInt

        [HttpPost()]
        public ActionResult checkNegInt(UnsafeValue testValue)
        {
            mdlTestResult ret = new mdlTestResult();

            ret.testResult = testValue.Validate<valNegInteger>().isValid; // note: this is a custom validator in this project's bizObjects namespace

            return Json(ret);
        }

        #endregion
        #region api - checkSimpleWord

        [HttpPost()]
        public ActionResult checkSimpleWord(UnsafeValue testValue)
        {
            mdlTestResult ret = new mdlTestResult();

            ret.testResult = testValue.Validate<valSingleWord>().isValid; // note: this validator is in the Unsafe.Data.Common.Validators namespace

            return Json(ret);
        }

        #endregion
        #region api - checkSimpleSentence

        [HttpPost()]
        public ActionResult checkSimpleSentence(UnsafeValue testValue)
        {
            mdlTestResult ret = new mdlTestResult();

            ret.testResult = testValue.Validate<valSimpleComment>().isValid; // note: this validator is in the Unsafe.Data.Common.Validators namespace

            return Json(ret);
        }

        #endregion



        #region api - checkDangerousID

        [HttpPost()]
        [ValidateInput(false)]
        public ActionResult checkDangerousID(UnsafeValue testValue)
        {
            mdlTestResult ret = new mdlTestResult();

            ret.testResult = testValue.Validate<valID>().isValid; // note: this validator is in the Unsafe.Data.Common.Validators namespace

            return Json(ret);
        }

        #endregion
        #region api - checkDangerousPosInt

        [HttpPost()]
        [ValidateInput(false)]
        public ActionResult checkDangerousPosInt(UnsafeValue testValue)
        {
            mdlTestResult ret = new mdlTestResult();

            ret.testResult = testValue.Validate<valPosInteger>().isValid; // note: this is a custom validator in this project's bizObjects namespace

            return Json(ret);
        }

        #endregion
        #region api - checkDangerousNegInt

        [HttpPost()]
        [ValidateInput(false)]
        public ActionResult checkDangerousNegInt(UnsafeValue testValue)
        {
            mdlTestResult ret = new mdlTestResult();

            ret.testResult = testValue.Validate<valNegInteger>().isValid; // note: this is a custom validator in this project's bizObjects namespace

            return Json(ret);
        }

        #endregion
        #region api - checkDangerousWord

        [HttpPost()]
        [ValidateInput(false)]
        public ActionResult checkDangerousWord(UnsafeValue testValue)
        {
            mdlTestResult ret = new mdlTestResult();

            ret.testResult = testValue.Validate<valSingleWord>().isValid; // note: this validator is in the Unsafe.Data.Common.Validators namespace

            return Json(ret);
        }

        #endregion
        #region api - checkDangerousSentence

        [HttpPost()]
        [ValidateInput(false)]
        public ActionResult checkDangerousSentence(UnsafeValue testValue)
        {
            mdlTestResult ret = new mdlTestResult();

            ret.testResult = testValue.Validate<valSimpleComment>().isValid; // note: this validator is in the Unsafe.Data.Common.Validators namespace

            return Json(ret);
        }

        #endregion

    }

}

Examples/WebApp/WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Setup()
        {
            return View();
        }

        public ActionResult InAction()
        {
            return View();
        }
    }
}

Examples/WebApp/WebApp/Controllers/InActionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class InActionController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }
    }
}

Examples/WebApp/WebApp/Views/Home/InAction.cshtml
@{
    ViewBag.Title = "In Action";
}
<div class="jumbotron">
    <h1>In Action</h1>
</div>


<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">Simple Tests</div>
        <div class="panel-body">

            <div class="container">
                <div class="input-group">

                    <span id="lblSimpleTest_Value" class="input-group-addon">Test Value</span>

                    <input id="txtSimpleTest_Value" type="text" class="form-control" placeholder="Enter A Value To Test" aria-describedby="lblSimpleTest_Value" value="1" >

                    <div class="input-group-btn">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Choose A Test&nbsp;&nbsp;&nbsp;<span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a id="lnkSimpleTest" href="#" data-testtype="1">Simple ID (akin to a database PK)</a></li>
                            <li><a id="lnkSimpleTest" href="#" data-testtype="2">Positive Interger</a></li>
                            <li><a id="lnkSimpleTest" href="#" data-testtype="3">Negative Integer</a></li>
                            <li><a id="lnkSimpleTest" href="#" data-testtype="4">Simple Word</a></li>
                            <li><a id="lnkSimpleTest" href="#" data-testtype="5">Simple Sentence</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="container bumpDown">
                <div class="input-group">
                    <span id="lblSimpleTest_Result" class="input-group-addon">Result</span>
                    <input id="txtSimpleTest_Result" type="text" class="form-control" placeholder="Click Run To Evaluate" aria-describedby="lblSimpleTest_Result" readonly="readonly" />
                </div>
            </div>

        </div>
    </div>

</div>


<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">More Dangerous Input Tests (No .NET input Validation)</div>
        <div class="panel-body">

            <div class="container">
                <div class="input-group">

                    <span id="lblDangerousTest_Value" class="input-group-addon">Test Value</span>

                    <input id="txtDangerousTest_Value" type="text" class="form-control" placeholder="Enter A Value To Test" aria-describedby="lblDangerousTest_Value" value="adsf <script>alert('xss')</script> asdf">

                    <div class="input-group-btn">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Choose A Test&nbsp;&nbsp;&nbsp;<span class="caret"></span></button>
                        <ul class="dropdown-menu">
                            <li><a id="lnkDangerousTest" href="#" data-testtype="1">Simple ID (akin to a database PK)</a></li>
                            <li><a id="lnkDangerousTest" href="#" data-testtype="2">Positive Interger</a></li>
                            <li><a id="lnkDangerousTest" href="#" data-testtype="3">Negative Integer</a></li>
                            <li><a id="lnkDangerousTest" href="#" data-testtype="4">Simple Word</a></li>
                            <li><a id="lnkDangerousTest" href="#" data-testtype="5">Simple Sentence</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="container bumpDown">
                <div class="input-group">
                    <span id="lblDangerousTest_Result" class="input-group-addon">Result</span>
                    <input id="txtDangerousTest_Result" type="text" class="form-control" placeholder="Click Run To Evaluate" aria-describedby="lblDangerousTest_Result" readonly="readonly" />
                </div>
            </div>

        </div>
    </div>

</div>


@section scripts {

<script type="text/javascript">
    $(document).ready(function () {

        $('a[id="lnkSimpleTest"]').click(function () {
            var value     = $("#txtSimpleTest_Value").val();
            var targetUrl = "/ajax/checkSomeID"; // default

            switch ($(this).data("testtype")) {
                case 1:
                    targetUrl = "/ajax/checkSomeID"
                    break;

                case 2:
                    targetUrl = "/ajax/checkPosInt"
                    break;

                case 3:
                    targetUrl = "/ajax/checkNegInt"
                    break;

                case 4:
                    targetUrl = "/ajax/checkSimpleWord"
                    break;

                case 5:
                    targetUrl = "/ajax/checkSimpleSentence"
                    break;
            }
        

            $.post(targetUrl, { testValue: value })
                .done(function (data) {
                    $("#txtSimpleTest_Result").val(data.testResult);
                })

                .fail(function (jqXHR, textStatus, errorThrown) {
                    $("#txtSimpleTest_Result").val("ERROR: " + errorThrown);
                });

        });






        $('a[id="lnkDangerousTest"]').click(function () {
            var value = $("#txtDangerousTest_Value").val();
            var targetUrl = "/ajax/checkDangerousID"; // default

            switch ($(this).data("testtype")) {
                case 1:
                    targetUrl = "/ajax/checkDangerousID"
                    break;

                case 2:
                    targetUrl = "/ajax/checkDangerousPosInt"
                    break;

                case 3:
                    targetUrl = "/ajax/checkDangerousNegInt"
                    break;

                case 4:
                    targetUrl = "/ajax/checkDangerousWord"
                    break;

                case 5:
                    targetUrl = "/ajax/checkDangerousSentence"
                    break;
            }


            $.post(targetUrl, { testValue: value })
                .done(function (data) {
                    $("#txtDangerousTest_Result").val(data.testResult);
                })

                .fail(function (jqXHR, textStatus, errorThrown) {
                    $("#txtDangerousTest_Result").val("ERROR: " + errorThrown);
                });

        });


    });
</script>

}

Examples/WebApp/WebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="jumbotron">
    <h1>Unsafe.MVC</h1>
    <p class="lead">This is an example site for the Unsafe.MVC library.</p>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Getting started</h2>
        <p>The Unsafe.MVC requires a little configuration in order to realize its full potential. This guide is the setup.</p>
        <p><a class="btn btn-default" href="/home/setup">Setup &raquo;</a></p>
    </div>
    <div class="col-md-6">
        <h2>In Action</h2>
        <p>See this page (and it's code) to review Unsafe.MVC in action!</p>
        <p><a class="btn btn-default" href="/home/inaction">Learn more &raquo;</a></p>
    </div>
</div>

Examples/WebApp/WebApp/Views/Home/Setup.cshtml
@{
    ViewBag.Title = "Setup";
}

<style type="text/css">
pre.spacer { margin-bottom: 25px; }
</style>

<div class="jumbotron">
    <h1>Setup</h1>
</div>

<div class="row">
    <div class="col-md-12">
        <h2>How to setup Unsafe.MVC</h2>
        <ol>
            <li>
                Download the nuget package...
                <pre class="spacer">PM> Install-Package Unsafe.MVC</pre>              
            </li>
            <li>
                Modify Global.asax to include Unsafe.MVC's BinderProvider in Application_Start()...
                <pre class="spacer">ModelBinderProviders.BinderProviders.Add(new Unsafe.MVC.UnsafeValueModelBinderProvider());</pre>
            </li>
            <li>
                Add UnsafeValue to the action's parameter
                <pre class="spacer">public ActionResult SomeActionName(UnsafeValue someParam)</pre>
            </li>
            <li>
                Use the built in validators in Unsafe.Data.Common.Validators...
                <pre>someParam.Validate&lt;valID&gt;().isValid;</pre>
                <pre class="spacer">someParam.Validate&lt;valID&gt;().value;</pre>
            </li>
            <li>
                ...or build your own!
                <pre>
public class valCustomChecker : UnsafeValidator<int>
{
&nbsp;&nbsp;&nbsp;&nbsp;public valCustomChecker(ref object value) : base(ref value)
&nbsp;&nbsp;&nbsp;&nbsp;{ }
&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;public override bool isValid
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;get
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;return false;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;}
}
                </pre>
                <pre>someParam.Validate&lt;valCustomChecker&gt;().isValid;</pre>
                <pre class="spacer">someParam.Validate&lt;valCustomChecker&gt;().value;</pre>
            </li>
        </ol>
    </div>
</div>

Examples/WebApp/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unsafe.MVC Example - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Unsafe.MVC Example", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse pull-right">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Setup", "Setup", "Home")</li>
                    <li>@Html.ActionLink("In Action", "InAction", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>